/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID || "oxxnjtwglhbbvxndpykk";
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94eG5qdHdnbGhiYnZ4bmRweWtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM1Nzc3NTEsImV4cCI6MjA4OTE1Mzc1MX0.w094qvixbkdbkF9k7ln9bygcjmNLykD1hUHOIPIkhNA";
export const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || `https://${projectId}.supabase.co`;
